### ISSUE TITLE
upgrade anyway postgres DB + postgis to latest stable version

### ISSUE THREAD

**Issue by OriHoch** [data-for-change/dfc-project-management#5]
create backup from prod
upgrade DB + restore on dev
test throughly on dev - anyway team will do that
if ok - create backup from prod
upgrade DB + restore on prod

**Comment by atalyaalon** [comment]
@OriHoch this is a priority right now since tests are failing

**Comment by atalyaalon** [comment]
In addition, postgres version should be newest, unless there is a technical difficulty with it.

**Comment by atalyaalon** [comment]
Thanks :)

**Comment by OriHoch** [comment]
@atalyaalon done on dev, please test and let me know when I can proceed to prod

**Comment by atalyaalon** [comment]
@OriHoch please proceed to prod and let me know when it’s done

**Comment by atalyaalon** [comment]
@OriHoch 
Will there be a downtime? What version did you upgrade to?

**Comment by OriHoch** [comment]
yes, there will be ~2 hours down time

**Comment by OriHoch** [comment]
postgres 15.1 + postgis 3.3.2

**Comment by atalyaalon** [comment]
Great, please upgrade, just let me know in advance before downtime starts

**Comment by atalyaalon** [comment]
Also, I assume this file will be also updated? [db dockerfile](https://github.com/hasadna/anyway/blob/dev/db_docker/Dockerfile)

**Comment by OriHoch** [comment]
> Great, please upgrade, just let me know in advance before downtime starts

I will try to do it today in the evening

> Also, I assume this file will be also updated? [db dockerfile](https://github.com/hasadna/anyway/blob/dev/db_docker/Dockerfile)

yes, db dockerfile is updated in hasadna/anyway#2300

**Comment by OriHoch** [comment]
starting upgrade

**Comment by OriHoch** [comment]
upgrade complete

**Comment by atalyaalon** [comment]
@OriHoch thank you very much
